# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'inkiMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for inkiMobile
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'inkiMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'RNSVG', :path => '../node_modules/react-native-svg'

    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'


  end

  target 'inkiMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end